// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestForABP.Infrastructure.Persistence;

#nullable disable

namespace TestForABP.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestForABP.Domain.Halls.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HallId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("amenities", (string)null);
                });

            modelBuilder.Entity("TestForABP.Domain.Halls.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("halls", (string)null);
                });

            modelBuilder.Entity("TestForABP.Domain.Halls.Amenity", b =>
                {
                    b.HasOne("TestForABP.Domain.Halls.Hall", null)
                        .WithMany("Amenities")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TestForABP.Domain.Halls.VO.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("AmenityId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("AmenityId");

                            b1.ToTable("amenities");

                            b1.WithOwner()
                                .HasForeignKey("AmenityId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("TestForABP.Domain.Halls.Hall", b =>
                {
                    b.OwnsOne("TestForABP.Domain.Halls.VO.Money", "BaseHourlyRate", b1 =>
                        {
                            b1.Property<Guid>("HallId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("base_hourly_rate");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("HallId");

                            b1.ToTable("halls");

                            b1.WithOwner()
                                .HasForeignKey("HallId");
                        });

                    b.OwnsOne("TestForABP.Domain.Halls.VO.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("HallId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("capacity");

                            b1.HasKey("HallId");

                            b1.ToTable("halls");

                            b1.WithOwner()
                                .HasForeignKey("HallId");
                        });

                    b.Navigation("BaseHourlyRate")
                        .IsRequired();

                    b.Navigation("Capacity")
                        .IsRequired();
                });

            modelBuilder.Entity("TestForABP.Domain.Halls.Hall", b =>
                {
                    b.Navigation("Amenities");
                });
#pragma warning restore 612, 618
        }
    }
}
